Repository tyuujitu/machikane23, pull requests merged in 2023-09, with the labels that each got.

#18 Feat/top
  package-lock.json
  src/App.js
  src/components/Footer.js
  src/components/Header.js
  src/css/About.css
  src/css/Common.css
  src/css/Footer.css
  src/css/Header.css
  src/css/Home.css
  src/imgs/circlecloud1.png
  src/imgs/circlecloud2.png
  src/imgs/circlecloud3.png
  src/imgs/logo.png
  src/imgs/main-visual-notitle.svg
  src/imgs/main-visual-title.svg
  src/pages/Home.js
  src/pages/access-map/Access.js
  src/pages/access-map/Map.js
  src/pages/machikane/About.js
  src/pages/machikane/Goods.js
  src/pages/machikane/Sponsor.js
  src/pages/machikane/Theme.js
  src/pages/project/LabOpen.js
  src/pages/project/OfficialProject.js
  src/pages/project/Project.js
  src/pages/project/Sections.js
  src/pages/project/Timetable.js
  src/pages/project/ralley.js
Labels: enhancement

#22 Feat/topの泳ぐ亀関連の変更しました
  public/index.html
  src/App.js
  src/components/Header.js
  src/css/Common.css
  src/css/Header.css
  src/css/Home.css
  src/pages/En-pages/HomeEn.js
  src/pages/Home.js
  src/pages/machikane/About.js
Labels: enhancement

#39 Feat/goods
  src/css/Goods.css
  src/imgs/goods/pen1.jpg
  src/imgs/goods/pen2.png
  src/imgs/goods/pen3.png
  src/imgs/goods/sticker1.jpg
  src/imgs/goods/sticker1.png
  src/imgs/goods/sticker2.jpg
  src/imgs/goods/sticker3.jpg
  src/imgs/goods/sticker4.jpg
  src/imgs/goods/sticker4.png
  src/imgs/goods/sticker5.png
  src/imgs/goods/totebag.png
  src/pages/machikane/Goods.js
Labels: enhancement

#43 Feat/goods
  src/css/Goods.css
  src/pages/machikane/Goods.js
Labels: enhancement

#53 引継ぎ終了
  src/css/Notes.css
  src/pages/visitor/Notes.js
Labels: bug

#76 Fix/talent project
  src/css/TalentProject.css
  src/pages/project/TalentProject.js
Labels: bug

#79 グラデーションをちょっといじった
  src/css/TalentProject.css
Labels: bug

#94 Feat/committee project
  src/css/OfficialProject.css
  src/css/TalentProject.css
  src/imgs/official_project/O-1.png
  src/imgs/official_project/bonber.png
  src/imgs/official_project/clock.png
  src/imgs/official_project/free.png
  src/imgs/official_project/house.png
  src/imgs/official_project/leaf.png
  src/imgs/official_project/leaf1.png
  src/imgs/official_project/machikaneForest.png
  src/imgs/official_project/nepleague.png
  src/imgs/official_project/pancake.png
  src/imgs/official_project/ticket.png
  src/pages/project/OfficialProject.js
  src/pages/project/TalentProject.js
Labels: bug, enhancement
